addSbtPlugin("org.scalameta"      % "sbt-scalafmt"   % "2.4.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.4.0")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"  % "0.10.0")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"       % "2.2.6")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"      % "1.4.3")
addSbtPlugin("com.geirsson"       % "sbt-ci-release" % "1.5.3")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"   % "0.9.20")
