addSbtPlugin("ch.epfl.scala"                     % "sbt-bloop"        % "1.4.5")
addSbtPlugin("ch.epfl.scala"                     % "sbt-scalafix"     % "0.9.24")
addSbtPlugin("com.eed3si9n"                      % "sbt-buildinfo"    % "0.10.0")
addSbtPlugin("com.geirsson"                      % "sbt-ci-release"   % "1.5.4")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.0")
addSbtPlugin("org.scalameta"                     % "sbt-mdoc"         % "2.2.13")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"     % "2.4.2")
addSbtPlugin("pl.project13.scala"                % "sbt-jmh"          % "0.4.0")
