name: Auto approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-22.04
    steps:
      - uses: hmarr/auto-approve-action@v4
        if: github.actor == 'zio-scala-steward[bot]' || github.actor == 'renovate[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
